name: Build .NET MAUI App Android

on:
  push:
    branches: [ "working_branch" ]
  pull_request:
    branches: [ "working_branch" ]

jobs:
  build:

    runs-on: windows-latest
    permissions: 
        contents: write
        pages: write

    steps:
      - uses: actions/checkout@v3
      - name: Setup Keystore File
        run:
          echo "${{ secrets.KEYSTORE_FILE }}" > myapp.keystore
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.x
      - name: Install .NET MAUI
        run: dotnet workload install maui
      - name: Restore dependencies
        run: dotnet restore
      - name: Build on Release Branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "heidi@negrete.dev"
          git checkout -b release
          dotnet build AcademicAssistant/AcademicAssistant.csproj -c:Release -f net8.0-android /p:AndroidSigningKeyStore=myapp.keystore /p:AndroidSigningKeyAlias=ghactionskey /p:AndroidSigningKeyPass="${{ secrets.KEYSTORE_PASSWORD }}" /p:AndroidSigningStorePass="${{ secrets.KEYSTORE_PASSWORD_ALIAS }}" --no-restore # may need to correct to -c Release
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path:
            ./**/*.apk
      - name: Publish build to Pages
        run: |
            mv ./**/*.apk ./academicassistant.apk
            touch index.html
            echo "<h1>EMC Academic Assistant</h1><p>Download the latest version of <a download="academic-assistant.apk" href='./academicassistant.apk'>EMC Academic Assistant</a>!</p>" > index.html
            git commit -am "Release build"
            git push origin release
